add search input
creative-system-consultant/csc-ca pull request #1
Opened 2023-11-08 10:50 UTC by safwanAzman

add search input

2023-11-09 01:36 UTC, nazirulfitrifauzi requested changes
buang yang ko komen kat permision.php & enable blik pagination yg ko komen tu.. aku tkot ko terkomen out tp lupe bukak blik

2023-11-09 01:36 UTC, nazirulfitrifauzi commented on resources/views/livewire/sys-admin/permission.blade.php
@safwanAzman Kenape ko comment kn pagination die?

2023-11-09 03:01 UTC, safwanAzman commented on resources/views/livewire/sys-admin/permission.blade.php
sebab aku nk tgk full hahaha

2023-11-09 03:30 UTC, nazirulfitrifauzi approved these changes
Done for now

2023-11-09 03:31 UTC, merged

2025-04-07 05:46 UTC, safwanAzman commented on resources/views/livewire/sys-admin/permission.blade.php
sorry do